version: '3'
services:
  fruitbasket:
    build: .
    ports:
      - "8080:8080"
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN:-0000}
    depends_on:
      - vault-secrets
      - vault
    #command: ["./vault/wait_for_vault.sh","0000", "java", "-jar", "/codeninja-fruit-basket.jar"]
    networks:
      - default

  vault:
    image: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN:-0000}
    networks:
      - default

  vault-secrets:
    build: vault-secrets/.
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=${VAULT_TOKEN:-0000}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_URL=${MYSQL_URL}
    networks:
      - default